export const REQUEST_TIMELINE = 'MEMORY/REQUEST_TIMELINE';
export const RECEIVE_TIMELINE = 'MEMORY/RECEIVE_TIMELINE';
export const CHANGE_DATATYPE = 'MEMORY/CHANGE_DATATYPE';

export const ADD_TODO = 'MEMORY/ADD_TODO';
export const SET_VISIBILITY_FILTER = 'MEMORY/SET_VISIBILITY_FILTER';
export const SET_TODO_ORDER = 'MEMORY/SET_TODO_ORDER';
export const TOGGLE_TODO_DONE = 'MEMORY/TOGGLE_TODO_DONE';
